# Disable sudo to speed up the build
sudo: false

# Set the build language to Python
language: python

# Set the python version to 3.7
python: 3.7

# Install the codecov pip dependency
install:
  - pip install codecov

# Run the unit test
script:
  - coverage run APIRequest_test.py
  - coverage run GetAllCards_test.py
  - coverage run GetAllCards_test_fail.py

# Push the results back to codecov
after_success:
  - codecov

